modLoader="javafml" # The mod loader type, Java FML for Forge
loaderVersion="[14,14.23.5]" # Loader version compatibility. Specify that this mod is meant for loader versions up to 14.23.5, non-inclusive of 14.23.6.
license="MIT"

[[mods]] # Start of the mods list
modId="resurgent-essentials"
version="0.2.0"
displayName="Resurgent Essentials"
description='''
This mod provides essential features for server-side functionality in Minecraft.
'''
authors="asonia"
credits="Team Resurgence"
logoFile=""
screenshots=[
]
dependencies=[
    "required:forge@[14.23.5.2854,14.23.5.2855)" # Specifies that this mod requires Forge exactly version 14.23.5.2854
]
side="SERVER" # This mod is server-side only
